version: "3.8"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - 4000:4000
  frontend:
    build: ./excel-perser-fe
    container_name: frontend_container
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
